# Generated by Django 3.1.4 on 2021-03-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_auto_20210318_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1),
        ),
    ]
