# Generated by Django 3.1.4 on 2021-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0006_auto_20210320_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='courses',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='education',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='languages',
            field=models.TextField(default=''),
        ),
    ]
