# Generated by Django 3.1.4 on 2021-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0007_auto_20210320_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='courses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeruser',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
