# Generated by Django 3.1.4 on 2021-03-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0009_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='city',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='country',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='state',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=45),
        ),
    ]
