# Generated by Django 3.1.4 on 2021-03-21 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0010_auto_20210320_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='job_applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
